version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
      timezone: Australia/Sydney
    open-pull-requests-limit: 20
    versioning-strategy: lockfile-only
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    ignore:
      - dependency-name: aws-partitions
        versions:
          - "> 1.329.0"
          - "< 2"
      - dependency-name: aws-sdk-core
        versions:
          - "> 3.99.1"
          - "< 4"
      - dependency-name: aws-sdk-kms
        versions:
          - "> 1.31.0"
          - "< 2"
      - dependency-name: aws-sdk-s3
        versions:
          - "> 1.66.0"
          - "< 2"
      - dependency-name: aws-sdk-sns
        versions:
          - "> 1.25.1"
          - "< 2"
      - dependency-name: aws-sigv4
        versions:
          - "> 1.2.0"
          - "< 2"
    groups:
      rails:
        patterns:
          - "actionmailer"
          - "actionpack"
          - "actionview"
          - "actionmodel"
          - "activerecord"
          - "activesupport"
          - "railties"
          - "sprockets-rails"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
      timezone: Australia/Sydney
    open-pull-requests-limit: 20
    versioning-strategy: increase
    ignore: # These are all vendored so need to be updated manually. See lib/tasks/javascript.rake
      - dependency-name: "ace-builds"
      - dependency-name: "@json-editor/json-editor"
      - dependency-name: "chart.js"
      - dependency-name: "chartjs-plugin-datalabels"
      - dependency-name: "diffhtml"
      - dependency-name: "magnific-popup"
      - dependency-name: "pikaday"
      - dependency-name: "moment"
      - dependency-name: "moment-timezone"
      - dependency-name: "@discourse/moment-timezon-names-translations"
      - dependency-name: "squoosh"
    groups:
      babel:
        patterns:
          - "@babel*"
      embroider:
        patterns:
          - "@embroider*"
      types:
        patterns:
          - "@types/*"
#  - package-ecosystem: "bundler"
#    directory: "migrations/config/gemfiles/convert"
#    schedule:
#      interval: "weekly"
#      day: "wednesday"
#      time: "10:00"
#      timezone: "Europe/Vienna"
#    versioning-strategy: "increase"
